[package]
name = "life-is-a-highway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2.2.4", features = ["postgres", "r2d2"] }
dotenvy = "0.15"
r2d2 = "0.8.10"
chrono = "0.4.38"
env_logger = "0.11.5"
serde = { version = "1.0.215", features = ["derive"] }