name: Rust CI

on: [ pull_request ]

jobs:
  rust-ci:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable
          cargo install cargo-llvm-cov

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
          cargo llvm-cov --version

      - name: Format
        run: |
          cargo fmt --all -- --check --color never

      - name: Check and Lint
        run: |
          cargo clippy --no-deps --tests -- -D warnings
      - name: Start Redis for Testing
        uses: supercharge/redis-github-action@1.5.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: latest
      - name: Test with Coverage
        env:
          TEST_CONFIG_BASE64_TOML: ${{ secrets.TEST_CONFIG_BASE64_TOML }}
        run: |
          # Inject TestConfig.toml from secret as file
          echo "$TEST_CONFIG_BASE64_TOML" | base64 -d > TestConfig.toml
          cargo llvm-cov --all --all-features test --color never